display_name: FlClash
package_name: flclash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

licenses:
  - GPL-3.0-or-later

icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator
  - libkeybinder3
  - libsecret

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - mihomo
  - Proxy

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/mihomo
  - x-scheme-handler/flclash

generic_name: FlClash

categories:
  - Network

startup_notify: true
startup_wm_class: com.follow.clash
